# name: Docker Image CI

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# jobs:

#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v4

#     - name: Get commit tag
#       id: get_tag
#       run: |
#         SHA=$(echo $GITHUB_SHA | head -c7)
#         echo "sha=$SHA" >> $GITHUB_OUTPUT

#     - name: Login to DockerHub
#       uses: docker/login-action@v3
#       with:
#         username: ${{ secrets.DOCKER_USERNAME }}
#         password: ${{ secrets.DOCKER_PASSWORD }}

#     # - name: Build the Docker image - Order Service for commit ${{ steps.get_tag.outputs.sha }}
#     #   run: docker build . --file order-service-api.Dockerfile --tag phoferr/order-service-api:${{ steps.get_tag.outputs.sha }}

#     # - name: Push the Docker image to DockerHub
#     #   run: docker push phoferr/order-service-api:${{ steps.get_tag.outputs.sha }}

#     - name: Build and push - Order Service
#       uses: docker/build-push-action@v6
#       with:
#         push: true
#         context: .
#         file: order-service-api.Dockerfile
#         tags: phoferr/order-service-api:${{ steps.get_tag.outputs.sha }}, phoferr/order-service-api:latest
